In [3]:
import pandas as pd
from datetime import datetime

In [7]:
df = pd.read_csv('tweet_data.csv')
df

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num
0,550441509175443456,VisualStockRSRC,1420070457,"lx21 made $10,008 on $AAPL -Check it out! htt...",0,0,1
1,550441672312512512,KeralaGuy77,1420070496,Insanity of today weirdo massive selling. $aap...,0,0,0
2,550441732014223360,DozenStocks,1420070510,S&P100 #Stocks Performance $HD $LOW $SBUX $TGT...,0,0,0
3,550442977802207232,ShowDreamCar,1420070807,$GM $TSLA: Volkswagen Pushes 2014 Record Recal...,0,0,1
4,550443807834402816,i_Know_First,1420071005,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1
...,...,...,...,...,...,...,...
3717959,1212159765914079234,TEEELAZER,1577836383,That $SPY $SPX puuump in the last hour was the...,1,0,6
3717960,1212159838882533376,ShortingIsFun,1577836401,In 2020 I may start Tweeting out positive news...,0,0,1
3717961,1212160015332728833,Commuternyc,1577836443,Patiently Waiting for the no twitter sitter tw...,0,0,5
3717962,1212160410692046849,MoriaCrypto,1577836537,I don't discriminate. I own both $aapl and $ms...,1,0,1
3717963,1212160477159206912,treabase,1577836553,"$AAPL #patent 10,522,475 Vertical interconnect...",0,0,0

In [8]:
def time_converter(time):
    ts = int(time)
    return str(datetime.utcfromtimestamp(ts).strftime('%Y'))

In [9]:
df['post_date'] =df['post_date'].map(time_converter)

In [10]:
df

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num
0,550441509175443456,VisualStockRSRC,2015,"lx21 made $10,008 on $AAPL -Check it out! htt...",0,0,1
1,550441672312512512,KeralaGuy77,2015,Insanity of today weirdo massive selling. $aap...,0,0,0
2,550441732014223360,DozenStocks,2015,S&P100 #Stocks Performance $HD $LOW $SBUX $TGT...,0,0,0
3,550442977802207232,ShowDreamCar,2015,$GM $TSLA: Volkswagen Pushes 2014 Record Recal...,0,0,1
4,550443807834402816,i_Know_First,2015,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1
...,...,...,...,...,...,...,...
3717959,1212159765914079234,TEEELAZER,2019,That $SPY $SPX puuump in the last hour was the...,1,0,6
3717960,1212159838882533376,ShortingIsFun,2019,In 2020 I may start Tweeting out positive news...,0,0,1
3717961,1212160015332728833,Commuternyc,2019,Patiently Waiting for the no twitter sitter tw...,0,0,5
3717962,1212160410692046849,MoriaCrypto,2019,I don't discriminate. I own both $aapl and $ms...,1,0,1
3717963,1212160477159206912,treabase,2019,"$AAPL #patent 10,522,475 Vertical interconnect...",0,0,0

In [11]:
def df_by_year(myList):
    list_of_dfs = []
    for year in myList:
        my_df = df.loc[df['post_date'] == year, :]
        list_of_dfs.append(my_df)
    return list_of_dfs

In [13]:
df_list = df_by_year(['2015','2016','2017','2018','2019'])
df_list

[                  tweet_id           writer post_date  \
 0       550441509175443456  VisualStockRSRC      2015
 1       550441672312512512      KeralaGuy77      2015
 2       550441732014223360      DozenStocks      2015
 3       550442977802207232     ShowDreamCar      2015
 4       550443807834402816     i_Know_First      2015
 ...                    ...              ...       ...
 727891  682711958483808257       IBD_NGondo      2015
 727892  682712177963347968      AMTrading24      2015
 727893  682712545002520576   roadrunnergreg      2015
 727894  682712548232187905      GregsHealth      2015
 727895  682712552338370560  ShayneHeffernan      2015

                                                      body  comment_num  \
 0       lx21 made $10,008  on $AAPL -Check it out! htt...            0
 1       Insanity of today weirdo massive selling. $aap...            0
 2       S&P100 #Stocks Performance $HD $LOW $SBUX $TGT...            0
 3       $GM $TSLA: Volkswagen Pushes 2014 Record Recal...            0
 4       Swing Trading: Up To 8.91% Return In 14 Days h...            0
 ...                                                   ...          ...
 727891  Happy New Year! Which dividend stocks should y...            0
 727892               Put back in my watchlist. $OFG $AAPL            0
 727893  US Stock Finished 2015 Under Pressure: US Stoc...            0
 727894  US Stock Finished 2015 Under Pressure: US Stoc...            0
 727895  US Stock Finished 2015 Under Pressure: US Stoc...            0

         retweet_num  like_num
 0                 0         1
 1                 0         0
 2                 0         0
 3                 0         1
 4                 0         1
 ...             ...       ...
 727891            3         3
 727892            0         1
 727893            0         0
 727894            0         0
 727895            1         0

 [727896 rows x 7 columns],
                    tweet_id           writer post_date  \
 727896   682712868064747520       amigobulls      2016
 727897   682712975996661760  Maximum_Pain_cm      2016
 727898   682713173837783040      DozenStocks      2016
 727899   682713776584396801     SeekingAlpha      2016
 727900   682713792246059008   igor_tsukerman      2016
 ...                     ...              ...       ...
 1570266  815341743881195526    PortfolioBuzz      2016
 1570267  815342609107402752     markbspiegel      2016
 1570268  815342662211375104          App_sw_      2016
 1570269  815343028751728641  SFBusinessTimes      2016
 1570270  815343560534921216     JuliaGrunfer      2016

                                                       body  comment_num  \
 727896   10 Reasons why $AAPL is underpriced - part 2 h...            0
 727897   $AMZN Max Pain = 680.00. Maturity = 12/31/2015...            0
 727898   Dow #Stocks Trend $GE $UTX $CAT $CSCO $PFE $PG...            0
 727899   Netflix: 2016 Outlook - Slight Chance Of Showe...            0
 727900   RT PassedPawnAdv: Tesla Motors Is On A Hiring ...            0
 ...                                                    ...          ...
 1570266  These assets are seeing a jump in tweets #fint...            0
 1570267  Hey by the way, all those "Elon Musk stream of...            1
 1570268  #Microsoft China's ivory ban marks a jumbo ste...            0
 1570269  The 14 highest-paying Bay Area #tech companies...            0
 1570270  The 14 highest-paying Bay Area #tech companies...            0

          retweet_num  like_num
 727896             0         0
 727897             0         0
 727898             0         0
 727899             4         1
 727900             0         0
 ...              ...       ...
 1570266            0         0
 1570267            0         1
 1570268            0         0
 1570269            4         0
 1570270            1         1

 [842375 rows x 7 columns],
                    tweet_id           writer post_date  \
 1570271  815346819710545920  anthonygutridge      2017
 1570272  815347055753359364    PortfolioBuzz      2017
 1570273  815348032287838209      MacHashNews      2017
 1570274  815349029022367745    letsinvestnow      2017
 1570275  815350096011280384    OphirGottlieb      2017
 ...                     ...              ...       ...
 2191288  947614615789240320       OACtrading      2017
 2191289  947615140492451840              NaN      2017
 2191290  947615215998423040       bubba67801      2017
 2191291  947615543539916800  Stonefoxcapital      2017
 2191292  947617461544812550     permabear_uk      2017

                                                       body  comment_num  \
 1570271  How To Improve Your #trading Using These 3 Key...            0
 1570272  See why these assets are trending in 1 watchli...            0
 1570273  Review: Bragi's Headphone offers a solid alter...            0
 1570274  $SPX $SPY $COMPQ $QQQ $RUT $DJIA $DIA $VIX $US...            0
 1570275  It feels like a secret, but there is an answer...            0
 ...                                                    ...          ...
 2191288  NOW OFFERING 7 Day FREE Trial to  options day ...            0
 2191289  Customized research for $POETF vs. $GOOG! #sto...            0
 2191290  Join @RobinhoodApp and we'll both get a share ...            0
 2191291                                 Commented on $AMZN            0
 2191292  $AAPL broke a new hist' high of $177.20, but s...            0

          retweet_num  like_num
 1570271            1         0
 1570272            0         0
 1570273            2         0
 1570274            1         2
 1570275            4         4
 ...              ...       ...
 2191288            0         0
 2191289            0         0
 2191290            0         1
 2191291            0         1
 2191292            1         3

 [621022 rows x 7 columns],
                     tweet_id           writer post_date  \
 2191293   947618374569353216          Auscomp      2018
 2191294   947618475958325248  ExactOptionPick      2018
 2191295   947619846124122113          Eric714      2018
 2191296   947622160616644610       OACtrading      2018
 2191297   947622701857832960   displayamerica      2018
 ...                      ...              ...       ...
 2958414  1079887952581459968      MemesOfMars      2018
 2958415  1079888458133327873      MacHashNews      2018
 2958416  1079888934291689472     GunGermSteel      2018
 2958417  1079889386836127745              NaN      2018
 2958418  1079889796401553408    sabotagebeats      2018

                                                       body  comment_num  \
 2191293  The 7 Greatest Tech Stocks of All Time monitor...            0
 2191294  Don't miss our next FREE OPTION TRADE.  Sign u...            0
 2191295  How is $AAPL @Apple going to get me to buy a #...            1
 2191296  REAL TIME TRADE ALERTS via PRIVATE $TWTR FEED,...            0
 2191297                           The Amazon Economy $AMZN            0
 ...                                                    ...          ...
 2958414   Happy New Year!  2019 the year for HEART of G...            3
 2958415  FCC to suspend most operations this week due t...            0
 2958416  $TSLA passed 190K model 3 VIN registered. Yeah...            0
 2958417  We're not ignoring it.Tesla CAN'T build it.$TS...            1
 2958418  Filing lawsuits against the SEC for manipulati...            1

          retweet_num  like_num
 2191293            0         2
 2191294            0         0
 2191295            0         0
 2191296            0         0
 2191297            0         0
 ...              ...       ...
 2958414            4        25
 2958415            0         0
 2958416            0         1
 2958417            1         9
 2958418            0         2

 [767126 rows x 7 columns],
                     tweet_id           writer post_date  \
 2958419  1079890068867817473       evdefender      2019
 2958420  1079890105282842629  ExactOptionPick      2019
 2958421  1079890627335213057   traderDanielle      2019
 2958422  1079890718326431745          O__rust      2019
 2958423  1079890782742503424     GunGermSteel      2019
 ...                      ...              ...       ...
 3717959  1212159765914079234        TEEELAZER      2019
 3717960  1212159838882533376    ShortingIsFun      2019
 3717961  1212160015332728833      Commuternyc      2019
 3717962  1212160410692046849      MoriaCrypto      2019
 3717963  1212160477159206912         treabase      2019

                                                       body  comment_num  \
 2958419  !!  8 Hours Left !!The picture you see here is...            6
 2958420  Don't miss our next FREE OPTION TRADE.  Sign u...            0
 2958421  Rinse and repeat - looking for entries in $XLC...            0
 2958422  $3750 would be the minimum discount in any cas...            0
 2958423  There are FUDking analysts like those from gol...            0
 ...                                                    ...          ...
 3717959  That $SPY $SPX puuump in the last hour was the...            1
 3717960  In 2020 I may start Tweeting out positive news...            0
 3717961  Patiently Waiting for the no twitter sitter tw...            0
 3717962  I don't discriminate. I own both $aapl and $ms...            1
 3717963  $AAPL #patent 10,522,475 Vertical interconnect...            0

          retweet_num  like_num
 2958419           16        82
 2958420            0         0
 2958421            0         3
 2958422            0         0
 2958423            0         1
 ...              ...       ...
 3717959            0         6
 3717960            0         1
 3717961            0         5
 3717962            0         1
 3717963            0         0

 [759545 rows x 7 columns]]

In [16]:
def df_to_csv(myList, years):
    i = 0
    for df in myList:
        df.to_csv(f'./tweet_data_by_year/tweet_data{years[i]}.csv')
        i+=1

In [17]:
df_to_csv(df_list,['2015','2016','2017','2018','2019'])